[package]
name = "edwards-curve-signature-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
num-bigint = "0.4.6"
sha2 = "0.10.9"
once_cell = "1.19"
regex = "1.12.2"
base64 = "0.22.1"
